/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IonPhaser {
    }
}
declare global {
    interface HTMLIonPhaserElement extends Components.IonPhaser, HTMLStencilElement {
    }
    var HTMLIonPhaserElement: {
        prototype: HTMLIonPhaserElement;
        new (): HTMLIonPhaserElement;
    };
    interface HTMLElementTagNameMap {
        "ion-phaser": HTMLIonPhaserElement;
    }
}
declare namespace LocalJSX {
    interface IonPhaser {
    }
    interface IntrinsicElements {
        "ion-phaser": IonPhaser;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ion-phaser": LocalJSX.IonPhaser & JSXBase.HTMLAttributes<HTMLIonPhaserElement>;
        }
    }
}
